In [20]:
import numpy as np

# 6x6 image matrix
image = np.array([[1, 1, 1, 1, 1, 1],
                  [1, 1, 1, 1, 1, 1],
                  [1, 1, 1, 0, 0, 1],
                  [1, 1, 1, 0, 0, 1],
                  [1, 1, 1, 1, 1, 1],
                  [1, 1, 1, 1, 1, 1]])

# 3x3 moving average filter
filter = np.array([[1/9, 1/9, 1/9],
                   [1/9, 1/9, 1/9],
                   [1/9, 1/9, 1/9]])

# Perform the convolution operation
output = np.zeros((4, 4))  

for i in range(4):
    for j in range(4):
        # Extract the 3x3 patch from the image
        patch = image[i:i+3, j:j+3]
        # Compute the element-wise multiplication and sum
        output[i, j] = np.sum(patch * filter)

# Print the resulting output matrix
print(output)

[[1.         0.88888889 0.77777778 0.77777778]
 [1.         0.77777778 0.55555556 0.55555556]
 [1.         0.77777778 0.55555556 0.55555556]
 [1.         0.88888889 0.77777778 0.77777778]]


# Architecture of VGG16

In [22]:
import torch
import torch.nn as nn
from torchvision import models
from torchsummary import summary

# importing the VGG16 model from PyTorch
vgg = models.vgg16()
summary(vgg, (3, 224, 224))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1         [-1, 64, 224, 224]           1,792
              ReLU-2         [-1, 64, 224, 224]               0
            Conv2d-3         [-1, 64, 224, 224]          36,928
              ReLU-4         [-1, 64, 224, 224]               0
         MaxPool2d-5         [-1, 64, 112, 112]               0
            Conv2d-6        [-1, 128, 112, 112]          73,856
              ReLU-7        [-1, 128, 112, 112]               0
            Conv2d-8        [-1, 128, 112, 112]         147,584
              ReLU-9        [-1, 128, 112, 112]               0
        MaxPool2d-10          [-1, 128, 56, 56]               0
           Conv2d-11          [-1, 256, 56, 56]         295,168
             ReLU-12          [-1, 256, 56, 56]               0
           Conv2d-13          [-1, 256, 56, 56]         590,080
             ReLU-14          [-1, 256,